"""add field is_combo

Revision ID: 5e3a47241f12
Revises: 63b98e8daeea
Create Date: 2025-06-06 16:19:35.728806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3a47241f12'
down_revision: Union[str, None] = '63b98e8daeea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_combo', sa.Boolean(), nullable=True))
    op.drop_column('products', 'is_giftset')
    op.drop_column('products', 'ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ingredients', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('is_giftset', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('products', 'is_combo')
    # ### end Alembic commands ###
