"""add field is_combo

Revision ID: e76eaaf0eb3f
Revises: 5e3a47241f12
Create Date: 2025-06-06 16:26:51.801867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76eaaf0eb3f'
down_revision: Union[str, None] = '5e3a47241f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
