"""Initial migration

Revision ID: f8e9a31002ce
Revises: 6a560c12b1de
Create Date: 2025-03-09 16:41:40.062735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e9a31002ce'
down_revision: Union[str, None] = '6a560c12b1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('original_price', sa.Float(), nullable=True))
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('products', 'original_price')
    op.drop_column('products', 'sale_price')
    # ### end Alembic commands ###
